version: '3.8'

# Development override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DATABASE_PATH=/app/database/notes.db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/frontend/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      - "5173:5173"  # Frontend dev server
    restart: "no"  # Don't restart in development
    
  # Remove nginx in development
  nginx:
    profiles:
      - disabled